---
- hosts: all
  tasks:
    - name: NTP Installation
      yum: name=ntp state=present
    - name: NTP Service
      service: name=ntpd state=started enabled=yes
    - name: NTP OS Package Installation
      package: name=ntp state=present
    - name: NTP File Configuration
      copy: src=/etc/ansible/test_folder/ntp.conf dest=/etc/ntp.conf
      notify:
        - restart ntp
    - name: To start NTP services
      service: name=ntpd state=started enabled=yes
  handlers:
    - name: restart ntp
      service: name=ntpd state=restarted
